set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-style "bg=default,fg=colour255"
set -g set-clipboard on
unbind r
bind r source-file ~/.tmux.conf ; display "Reloaded ~/.tmux.conf"
set -g base-index 1
set -g renumber-windows on
set -g prefix C-s
wg_prfx="#{?client_prefix,<Prefix> ,}"
set -g status-right "${wg_prfx}"
set -g mouse on
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
