#!/usr/bin/env node
var fs = require('node:fs');
var { execSync } = require('node:child_process');
var path = require('node:path');

var run = (command, options) => execSync(command, { ...options, stdio: 'inherit' });

var dotfiles = path.join(__dirname, 'dotfiles');
var home = process.env.HOME;
fs.cpSync(dotfiles, home, { recursive: true });

run('apt update && apt install ripgrep python3.12-venv -y');

fs.existsSync('e2e/install.sh') && run('e2e/install.sh');

var hasNeovim = fs.existsSync('/opt/wf-state/neovim/bin/nvim');
!hasNeovim && ((nvim_path) => (
  run('apt install ninja-build gettext cmake curl build-essential -y'),
  run(`git clone --branch stable https://github.com/neovim/neovim ${nvim_path}`),
  run(
    'make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/opt/wf-state/neovim"',
    { cwd: nvim_path }
  ),
  run('make install', { cwd: nvim_path })
))(path.join(process.env.HOME, 'neovim'));

[
  path.join(__dirname, 'bash/nvim-postinstall.sh'),
  path.join(__dirname, 'bash/prompt.sh'),
].forEach(p => run(`source ${p}`));

((nvim_config_path) => 
  run(`git clone "https://github.com/alex-teder/nvim-config-v2.git" ${nvim_config_path}`)
)(path.join(process.env.HOME, '.config', 'nvim'));

run('npm i -g typescript-language-server');

console.log(`
                      _                        
                      \´*-.                    
                       )  _´-.                 
                      .  : ´. .                
                      : _   '  \               
                      ; *´ _.   ´*-._          
                      ´-.-'          ´-.       
                        ;       ´       ´.     
                        :.       .        \    
                        . \  .   :   .-'   .   
                        '  ´+.;  ;  '      :   
                        :  '  |    ;       ;-. 
                        ; '   : :´-:     _.´* ;
    [happy coding]   .*' /  .*' ; .*´- +'  ´*' 
                     ´*-*   ´*-*  ´*-*'`);
