#!/usr/bin/env node
var fs = require('node:fs');
var { execSync, spawnSync } = require('node:child_process');
var path = require('node:path');

var run = (command, options) => execSync(command, { ...options, stdio: 'inherit' });

var dotfiles = path.join(__dirname, 'dotfiles');
var home = process.env.HOME;
fs.cpSync(dotfiles, home, { recursive: true });

run('apt update && apt install ripgrep starship zoxide -y');

// fs.existsSync('e2e/install.sh') && run('e2e/install.sh');

var hasNeovim = fs.existsSync('/opt/wf-state/neovim/bin/nvim');
!hasNeovim && ((nvim_path) => (
  run('apt install ninja-build gettext cmake curl build-essential -y'),
  run(`git clone --depth 1 https://github.com/neovim/neovim ${nvim_path}`),
  run(
    'make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/opt/wf-state/neovim"',
    { cwd: nvim_path }
  ),
  run('make install', { cwd: nvim_path })
))(path.join(process.env.HOME, 'neovim'));

var hasTreeSitter = spawnSync('which', ['tree-sitter'], { stdio: "ignore" }).status === 0;
!hasTreeSitter && (() => {
  run("curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash")
  run("~/.cargo/bin/cargo-binstall tree-sitter-cli -y")
})();

fs.appendFileSync(
  path.join(process.env.HOME, '.bashrc'),
  `\nsource ~/.bashrc.d/dotfiles.sh`
);

((nvim_config_path) => 
  run(`git clone "https://github.com/alex-teder/nvim-smol.git" ${nvim_config_path}`)
)(path.join(process.env.HOME, '.config', 'nvim'));

console.log(`
                      _                        
                      \´*-.                    
                       )  _´-.                 
                      .  : ´. .                
                      : _   '  \               
                      ; *´ _.   ´*-._          
                      ´-.-'          ´-.       
                        ;       ´       ´.     
                        :.       .        \    
                        . \  .   :   .-'   .   
                        '  ´+.;  ;  '      :   
                        :  '  |    ;       ;-. 
                        ; '   : :´-:     _.´* ;
    [happy coding]   .*' /  .*' ; .*´- +'  ´*' 
                     ´*-*   ´*-*  ´*-*'`);
